package com.camptool.classes

import java.util.*

data class Kid(
    var uuid: String = "",
    val name: String = "",
    val contact: List<List<String>> = listOf(),
    val info: List<String> = listOf(),
    var needs: List<String> = listOf(),
    var history: List<String> = listOf(),
    var notes: List<String> = listOf()
)

val names = listOf(
    "Anna",
    "Maria",
    "Katarzyna",
    "Małgorzata",
    "Agnieszka",
    "Krystyna",
    "Barbara",
    "Ewa",
    "Elżbieta",
    "Zofia",
    "Janina",
    "Magdalena",
    "Jadwiga",
    "Aleksandra",
    "Halina",
    "Danuta",
    "Irena",
    "Ewelina",
    "Marta",
    "Dorota",
    "Beata",
    "Agata",
    "Alicja",
    "Natalia",
    "Joanna",
    "Patrycja",
    "Weronika",
    "Kinga",
    "Paulina",
    "Kamila",
    "Helena",
    "Justyna",
    "Karolina",
    "Monika",
    "Klaudia",
    "Jolanta",
    "Martyna",
    "Renata",
    "Kornelia",
    "Ludmiła",
    "Aneta",
    "Izabela",
    "Sandra",
    "Adrianna",
    "Olga",
    "Dominika",
    "Urszula",
    "Karina",
    "Teresa",
    "Sylwia",
    "Jan",
    "Andrzej",
    "Piotr",
    "Krzysztof",
    "Stanisław",
    "Tomasz",
    "Paweł",
    "Józef",
    "Marcin",
    "Michał",
    "Grzegorz",
    "Jerzy",
    "Tadeusz",
    "Marek",
    "Wojciech",
    "Adam",
    "Zbigniew",
    "Ryszard",
    "Jakub",
    "Krystian",
    "Kamil",
    "Mateusz",
    "Łukasz",
    "Robert",
    "Roman",
    "Filip",
    "Artur",
    "Maciej",
    "Dariusz",
    "Rafał",
    "Mariusz",
    "Bartosz",
    "Kacper",
    "Stefan",
    "Władysław",
    "Szymon",
    "Przemysław",
    "Czesław",
    "Wiktor",
    "Henryk",
    "Aleksander",
    "Karol",
    "Lech",
    "Daniel",
    "Leon",
    "Mieczysław",
    "Igor",
    "Dawid",
    "Radosław",
    "Arkadiusz"
)

val surnames = listOf(
    "Nowak",
    "Kowalski",
    "Wiśniewski",
    "Dąbrowski",
    "Lewandowski",
    "Wójcik",
    "Kamiński",
    "Kowalczyk",
    "Zieliński",
    "Szymański",
    "Woźniak",
    "Dąbrowska",
    "Kozłowski",
    "Jankowski",
    "Wojciechowski",
    "Kwiatkowski",
    "Kaczmarek",
    "Piotrowski",
    "Grabowski",
    "Nowakowski",
    "Pawłowski",
    "Michalski",
    "Nowicki",
    "Adamczyk",
    "Dudek",
    "Zając",
    "Wieczorek",
    "Jabłoński",
    "Król",
    "Majewski",
    "Olszewski",
    "Jaworski",
    "Wróbel",
    "Malinowski",
    "Pawlak",
    "Witkowski",
    "Walczak",
    "Stępień",
    "Górski",
    "Rutkowski",
    "Michalak",
    "Sikora",
    "Ostrowski",
    "Baran",
    "Duda",
    "Szewczyk",
    "Tomaszewski",
    "Pietrzak",
    "Marciniak",
    "Wróblewski",
    "Zalewski",
    "Jakubowski",
    "Jasiński",
    "Zawadzki",
    "Sadowski",
    "Bąk",
    "Chmielewski",
    "Włodarczyk",
    "Borkowski",
    "Czarnecki",
    "Sawicki",
    "Sokołowski",
    "Urbański",
    "Kubiak",
    "Maciejewski",
    "Szczepański",
    "Kucharski",
    "Wilk",
    "Kalinowski",
    "Lis",
    "Mazurek",
    "Wysocki",
    "Adamski",
    "Kaźmierczak",
    "Wasilewski",
    "Sobczak",
    "Czerwiński",
    "Andrzejewski",
    "Cieślak",
    "Głowacki",
    "Zakrzewski",
    "Kołodziej",
    "Sikorski",
    "Krajewski",
    "Gajewski",
    "Szymczyk",
    "Krupa",
    "Lewicki",
    "Gajda",
    "Klimek",
    "Kulesza",
    "Piątek",
    "Leszczyński",
    "Markowski",
    "Kozak",
    "Mikołajczyk",
    "Brzeziński",
    "Jarosz",
    "Musiał",
    "Zięba",
    "Kopeć",
    "Łuczak",
    "Dziedzic",
    "Nowacki",
    "Kot",
    "Stankiewicz",
    "Romanowski",
)

fun generatePhoneNumber(): String {
    val areaCode = (100..999).random()
    val middleThree = (100..999).random()
    val lastThree = (100..999).random()
    return "$areaCode $middleThree $lastThree"
}

fun generateContact(surname: String): List<List<String>> {
    val roles = listOf("Rodzic", "Opiekun")
    return listOf(
        listOf("${names.random()} $surname", roles.random(), generatePhoneNumber()),
        listOf("${names.random()} $surname", roles.random(), generatePhoneNumber())
    )
}

fun generateInfo(): List<String> {
    val allergies = listOf("orzechy", "pyłki", "sierść zwierząt")
    val traits = listOf("spokojnośc", "energiczność", "nieśmiałość")
    return listOf(
        "alergia na ${allergies.random()}",
        "cechy: ${traits.random()}"
    )
}

fun generateHistory(): List<String> {
    val events = listOf(
        "przewrócenie się",
        "ugryzienie przez owada",
        "złamanie nogi",
        "podrażnienie skóry"
    )
    return listOf(events.random())
}

val kids = List(50) {
    val name = names.random()
    val surname = surnames.random()

    Kid(
        UUID.randomUUID().toString().replace("-", "").uppercase(Locale.getDefault()),
        "$name $surname",
        generateContact(surname),
        generateInfo(),
        listOf(),
        generateHistory(),
        listOf()
    )
}